### ISSUE TITLE
[Feature]: tvOS Support

### ISSUE THREAD

**Issue by loganblevins** [braze-inc/braze-swift-sdk#1]
### What problem are you facing?

Just received the early access email noting lack of tvOS support. Voting for this feature here.

### Workarounds

No workarounds.

**Comment by lowip** [comment]
Hi @loganblevins,

We have released [5.3.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.3.0) which adds support for tvOS. 
Don't hesitate to check out the [Examples](https://github.com/braze-inc/braze-swift-sdk/tree/main/Examples) project which contains a few tvOS specific schemes.

**Comment by loganblevins** [comment]
@lowip Thanks for followup! I will give this a shot and report back if needed.
