### ISSUE TITLE
[Bug]: Migrating new SDK - missing methods and variables

### ISSUE THREAD

**Issue by YardenDvash** [braze-inc/braze-swift-sdk#10]
### Platform

iOS

### Platform Version

iOS 14

### Braze SDK Version

Latest

### Xcode Version

13.3

### Computer Processor

Apple (M1)

### Repro Rate

100

### Steps To Reproduce

We are migrating the new BrazeKit SDK instead of the old AppBoy SDK,
But I found there some methods and variables that aren't available, for example:

Appboy.disableSDK()
Appboy.requestEnableSDKOnNextAppRun()

Are you intent to add them in future release? or they are no longer needed? and we can deprecate them safely? 

Plus, we used to fetch `urlString` from the old content card (ABK...) and with the new Braze.ContentCard - the variable are missing...

### Expected Behavior

.

### Actual Incorrect Behavior

.

**Comment by lowip** [comment]
Hi @YardenDvash, thanks for opening this issue.

We are still in the process of writing our migration guide, you can track our _Upcoming Feature Roadmap_ [here](https://github.com/braze-inc/braze-swift-sdk/#upcoming-feature-roadmap).

To answer your questions:

> But I found there some methods and variables that aren't available, for example:
>
> Appboy.disableSDK()
> Appboy.requestEnableSDKOnNextAppRun()

In the Swift SDK, you can use the `enabled` [property](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/enabled) on the `braze` instance:

```swift
// Disable the SDK, stays disabled even accross app launches
braze.enabled = false

// Re-enable the SDK at any time
braze.enabled = true
```

Alternatively, if storing your `braze` instance as an `Optional`:

```swift
// Destroy the braze instance
AppDelegate.braze = nil

// Re-create a new braze instance at any time
AppDeleage.braze = Braze(configuration: /* ... */)
```

> Plus, we used to fetch urlString from the old content card (ABK...) and with the new Braze.ContentCard - the variable are missing...

You can access the url via the card's [`clickAction`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcard/data-swift.struct/clickaction) property:

```swift
// Get the click action:
let clickAction = card.data.clickAction

// The `data` key path can be omitted
let clickAction = card.clickAction

// Extract the url from the click action
if case .uri(let uri, let useWebView) = clickAction {
  print("Content Card uri:", uri)
}
```

In the next release of the SDK, you will be able to simply write:

```swift
if let url = card.clickAction.uri {
  // Do something with the url
}
```

I'm closing the issue as you should have everything needed here. If that's not the case, feel free to re-open the issue with additional details.

Thanks,
