### ISSUE TITLE
[Bug]: Braze Payload issue

### ISSUE THREAD

**Issue by BrazeCJ** [braze-inc/braze-swift-sdk#100]
### Platform

iOS

### Platform Version

iOS 14] + 

### Braze SDK Version

5.11.0

### Xcode Version

Xcode 14.2

### Computer Processor

Intel

### Repro Rate

100%

### Steps To Reproduce

1. iOS Setting(method didFinishLaunchingWithOptions) excepts for silent push
2. Push with Braze campaigns
3. Run to app(Background Mode)

<img width="648" alt="1  iOS Setting excepts for silent push" src="https://github.com/braze-inc/braze-swift-sdk/assets/142372954/91cd81b0-7b6a-48fd-92ba-7cf8bc939b06">

### Expected Behavior

Push Payload information(field name : ab) is not being called correctly.
This prevented the app from activating properly in background mode.

### Actual Incorrect Behavior

Push Payload information(field name : ab) is not being called correctly.
This prevented the app from activating properly in background mode.

**Comment by jerielng** [comment]
Hi @BrazeCJ, could you provide a little more details around your testing? Are you able to debug where the failure point is in your code? Specifically, in your `else` block, can you confirm where exactly you are not getting the values you are expecting (i.e. is the `launchOptions` nil, is the `remoteNotification` nil, etc.)?

From our end, I am not able to reproduce a scenario where the `"ab"` contents are not present in the push payload. It's worth pointing out that we typically check and process the push payload in the `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` delegate method for handling silent/background notifications, per the integration [tutorial](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b1-standard-push-notifications). Is there a specific reason you are relying on `didFinishLaunchingWithOptions`?

**Comment by BrazeCJ** [comment]
Hi @jerielng ,

Thanks you for answer.

Are you able to debug where the failure point is in your code?
answer : below the image and The issue occurs at the time of the push click while the app is closed.
<img width="546" alt="스크린샷 2024-01-04 오전 9 07 24" src="https://github.com/braze-inc/braze-swift-sdk/assets/142372954/e7efa889-c952-4969-87f6-6b5bc2ff56fd">

Is there a specific reason you are relying on didFinishLaunchingWithOptions
answer : They do not want to recieve silent push so they set Braze Slient Push exceptions.

**Comment by jerielng** [comment]
Hey @BrazeCJ, thanks - in that screenshot, more specifically, could you specify which of those three objects is coming back `nil`? Figuring out which one is not populating would help pinpoint if it's an issue inside the Braze payload or something in the UserNotifications framework.

If possible, it would be helpful to gather all of this information, along with a relevant campaign that you are using to test, to send to our support team at support@braze.com and then reference this GitHub issue for additional context.

**Comment by BrazeCJ** [comment]
Hi @jerielng 

I hope you are doing well.

Information coming in as nil means "ab" in the Payload field

Thanks

**Comment by jerielng** [comment]
@BrazeCJ Are you able to log and share what the payload of your `remoteNotification` object contains?

**Comment by hokstuff** [comment]
Hi @BrazeCJ,

Are you still experiencing this issue? It will likely be easier to converse via our Support channels at support@braze.com to share any relevant code and behaviors you are seeing. Thanks!
