### ISSUE TITLE
[Feature]: In App Message Dynamic Type support for accessibility. 

### ISSUE THREAD

**Issue by JonHillAtStitchFix** [braze-inc/braze-swift-sdk#101]
### What problem are you facing?

In testing In App Messages, it appears that dynamic type is not supported for in app messages. 

### Workarounds

I am not aware of any workarounds. 

### Ideal Solution

The braze provided UI should respect the users dynamic type settings.

**Comment by lowip** [comment]
Hi @JonHillAtStitchFix,

We do support dynamic type in in-app messages, but this does not apply to HTML based in-app messages. Could you provide more information regarding your test scenario?

Thanks

**Comment by hokstuff** [comment]
I'm closing this out due to possible staleness. Please contact support@braze.com with further context about the issue you are facing - thanks!
