### ISSUE TITLE
[Bug]: Wrong SDK version logged for 8.0.0

### ISSUE THREAD

**Issue by ullstrm** [braze-inc/braze-swift-sdk#104]
### Platform

iOS

### Platform Version

17.3.1

### Braze SDK Version

8.0.0

### Xcode Version

15.2.0

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Upgrade to 8.0.0 with SPM
  2. Run the app.

### Expected Behavior

`Initializing Braze SDK 8.0.0 with configuration:` should be printed.

### Actual Incorrect Behavior

`Initializing Braze SDK 7.7.0 with configuration:` is printed.

**Comment by lowip** [comment]
Hi @ullstrm, we've just released [8.0.1](https://github.com/braze-inc/braze-swift-sdk/releases/tag/8.0.1) which resolves this issue. Thanks for bringing this up to our attention!
