### ISSUE TITLE
[Bug]: Linker failure when using Xcode 15.0 + BrazeKit 8.2.1 

### ISSUE THREAD

**Issue by andre-alves** [braze-inc/braze-swift-sdk#115]
### Platform

iOS

### Platform Version

iOS 17

### Braze SDK Version

8.2.1

### Xcode Version

Xcode 15.0

### Computer Processor

Apple (M1)

### Repro Rate

100% of the time

### Steps To Reproduce

- Use Xcode 15.0
- Create new project
- File -> Add Package Dependencies
- Add braze-swift-sdk, include all SDKs into the main app
- Try to build
- ld failure

Here is the repro:  [TestBraze.zip](https://github.com/braze-inc/braze-swift-sdk/files/14705258/TestBraze.zip)

### Expected Behavior

Expected to build the app.

### Actual Incorrect Behavior

<img width="1512" alt="image" src="https://github.com/braze-inc/braze-swift-sdk/assets/7773955/418f9c4d-bbfc-47ee-8cd3-fbc0a87a1cc9">

### Verbose Logs

```shell
ld: Undefined symbols:
  static ActivityKit.Activity.pushToStartTokenUpdates.getter : ActivityKit.Activity<A>.PushTokenUpdates, referenced from:
      (1) suspend resume partial function for closure #2 @Sendable () async -> () in BrazeKit.Braze.LiveActivities.registerPushToStart<A where A: ActivityKit.ActivityAttributes, A: BrazeKit.BrazeLiveActivityAttributes>(forType: ActivityKit.Activity<A>.Type, name: Swift.String) -> Swift.Task<(), Swift.Never> in BrazeKit[arm64][2](BrazeKit-arm64-master.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hokstuff** [comment]
Hi @andre-alves,

This error is actually expected, since as of [version 8.0.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/8.0.0) we compile our SDK using Xcode 15.2. In order to use an updated version of the SDK, you would need to update to Xcode 15.2+. If you need to use Xcode 15.0, feel free to use a version of our SDK prior to 8.0.0.

Thanks!
