### ISSUE TITLE
[Bug]: BrazePushStory is not working as expected while legacy AppboyPushStory is working well

### ISSUE THREAD

**Issue by layneios** [braze-inc/braze-swift-sdk#120]
### Platform

iOS

### Platform Version

iOS 16.7

### Braze SDK Version

7.5.0

### Xcode Version

Xcode 15.3

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

We want to migrate AppboyPushStory to BrazePushStory.
1. Follow this step: https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide#Push-Stories-Notifications
2. Create a Notification Content Extension following this tutorial: https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b3-push-stories
3. The code in `NotificationViewController` is the same as tutorial. `import BrazePushStory
class NotificationViewController: BrazePushStory.NotificationViewController {}`.
4. Send a push story notification from Braze console (Notification type: Push Stories).
5. Our app receives a notification.
6. LongPress the notification, just **shows a blank view**.

### Expected Behavior

Shows the push story view same as the legacy AppboyPushStory SDK. Same as the Preview on Braze console as well.

### Actual Incorrect Behavior

Just **shows a blank view**

**Comment by hokstuff** [comment]
Hi @layneios,

It sounds like there is an integration error in your extension. Can you verify a few things:
1. Have you confirmed that you have successfully integrated [the App Group](https://developer.apple.com/documentation/xcode/configuring-app-groups) in your host app?
2. Can you verify that your minimum deployment target for the Push Story extension matches the version in the main app target?

If the above investigation doesn't help, can you contact support@braze.com with more information around your integration so the team can take a deeper look?

Thanks!

**Comment by hokstuff** [comment]
I am closing this ticket out due to inactivity. As noted above, please contact our Support team for more catered support for your issue. Thanks!
