### ISSUE TITLE
[Bug]:  Crash in Xcode16 beta1/iOS18 beta

### ISSUE THREAD

**Issue by pavm035** [braze-inc/braze-swift-sdk#131]
### Platform

iOS

### Platform Version

iOS 18

### Braze SDK Version

8.2.1

### Xcode Version

Xcode 16

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

1.  Add Braze/BrazeUI as dependency via SPM
2. Run the app and observer the crash

### Expected Behavior

Crash shouldn't happen

### Actual Incorrect Behavior

Crash

### Verbose Logs

```shell
dyld[1463]: Library not loaded: @rpath/lib/libswiftCoreGraphics.dylib
  Referenced from: <AF9553CE-243A-3766-A3CB-3AD172EA6849> /private/var/containers/Bundle/Application/7F968F8F-A134-45DD-95F7-9BF2C1EBBC14/<APP_NAMR>.app/Frameworks/BrazeUI_30A23D419F0B5719_PackageProduct.framework/BrazeUI_30A23D419F0B5719_PackageProduct
  Reason: tried: '/usr/lib/system/introspection/libswiftCoreGraphics.dylib' (no such file, not in dyld cache), '/usr/lib/swift/lib/libswiftCoreGraphics.dylib' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/lib/libswiftCoreGraphics.dylib' (no such file),
```

**Comment by lowip** [comment]
Hi @pavm035,

Thanks for reporting this issue, the logs clearly mentions `BrazeUI` though we haven't been able to reproduce this issue yet. Does the crash occurs when running your application on devices, simulators or both?

Could you try integrating Braze using our alternative static prebuilt repository: https://github.com/braze-inc/braze-swift-sdk-prebuilt-static
It might help resolves the issue while we investigate the main repository.

**Comment by pavm035** [comment]
The issue happens only on Device but simulator is ok

I will try other repo and share you the results

**Comment by lowip** [comment]
Hey @pavm035,

We were able to reproduce this issue with a device running the iOS 18 beta. Apple is aware of that issue (thread [here](https://developer.apple.com/forums/thread/756658)). For now, the workaround is to increase the minimum deployment target to iOS 13.

Using the alternative repository https://github.com/braze-inc/braze-swift-sdk-prebuilt-static does not help in that case.

We expect this issue to be resolved in a future beta, as a result, I'm closing this ticket.

Best,

**Comment by pavm035** [comment]
Hi @lowip 
Thanks for checking, but our deployment target is already iOS 15.0, anyways it might be a known issue to apple will be keep watching this issue until next betas
