### ISSUE TITLE
[Bug]: Not getting Bool to decide to opening of URL through WebView or external browser

### ISSUE THREAD

**Issue by asadkazmi-mset** [braze-inc/braze-swift-sdk#136]
### Platform

iOS

### Platform Version

17.2

### Braze SDK Version

7.7.0

### Xcode Version

15.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Adding this line "contentCard.openUrlInWebView" is no longer working in the new verison of braze swift sdk
  2. compile time error "Value of type 'Braze.ContentCard' has no dynamic member 'openUrlInWebView' using key path from root type 'Braze.ContentCard.Data'"

### Expected Behavior

this must suggest to use of alternate variables instead of this

### Actual Incorrect Behavior

It is not suggesting the alternate variable, and when I jump to SDK code there are no any webview related variable there in the `Braze.ContentCard`
But I can see the alternate of `"openWebView"` in Braze.NewsFeed that is `"useWebView"`, so there should be something for `Braze.ContentCard`

### Additional Information

This is the error when I'm trying to access the `"openUrlInWebView"` in the case of content card
<img width="773" alt="Screenshot 2024-08-06 at 1 00 44 PM" src="https://github.com/user-attachments/assets/8c8e8beb-f316-48e3-87a9-d74af17e3b89">

But able to see the alternat of `"openUrlInWebView"` in the case of NewsFeed that is `"useWebView"`
<img width="356" alt="Screenshot 2024-08-06 at 1 01 04 PM" src="https://github.com/user-attachments/assets/78aec2ca-c898-4107-9463-f1003a4b49cd">

Please suggest me the alternate of openURLInWebView (Bool) for content card. 

Thanks.

**Comment by jerielng** [comment]
Hi @asadkazmi-mset, the `useWebView` property should live inside the [ClickAction](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcard/clickaction/url(_:usewebview:)) enum property of that `Braze.ContentCard`. So you can access it like this:
```swift
if case let .url(url, useWebView) = contentCard.clickAction {
  print(useWebView)
}
```

**Comment by asadkazmi-mset** [comment]
Thank you @jerielng

**Comment by jerielng** [comment]
No problem @asadkazmi-mset! I'll close out this issue now, but feel free to reach back out if you have any additional questions. Thanks!
