### ISSUE TITLE
[Bug]: ITMS-91107: Invalid tracking information

### ISSUE THREAD

**Issue by vicsuccess** [braze-inc/braze-swift-sdk#138]
### Platform

iOS

### Platform Version

iOS 18.0

### Braze SDK Version

8.4.0

### Xcode Version

Xcode 15.3

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

When registering for App Store review, I received the following warning email. Please resolve it.

==========================================================================================

Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.

ITMS-91107: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “braze-swift-sdk_BrazeKitResources.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in any privacy manifest must be valid. For more details, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

Apple Developer Relations

### Expected Behavior

may be rejected

### Actual Incorrect Behavior

Issue fix

**Comment by vicsuccess** [comment]
Was it resolved in version 9.0.0 SDK?
* https://github.com/braze-inc/braze-swift-sdk/issues/126#issuecomment-2080134400

**Comment by hokstuff** [comment]
Hi @vicsuccess,

Please update to the latest Swift SDK version and it should fix your issue. If it doesn't feel free to open a new issue with details and logs.

Thanks!

**Comment by vicsuccess** [comment]
HI @hokstuff 
Thank you for your quick reply.
