### ISSUE TITLE
Xcode 16/ iOS18 Compatibility check

### ISSUE THREAD

**Issue by pavm035** [braze-inc/braze-swift-sdk#141]
### Platform

iOS

### Platform Version

iOS 18

### Braze SDK Version

8.2.1

### Xcode Version

Xcode 16

### Computer Processor

Apple (M1)

### Repro Rate

NA

### Steps To Reproduce

Hi,

This is just general query to confirm the official Braze SDK version that's compatible with Xcode 16/iOS18

Current version we are using: 8.2.1

### Expected Behavior

NA

### Actual Incorrect Behavior

NA

**Comment by lowip** [comment]
Hi @pavm035,

Your version of the Swift SDK is compatible with Xcode 16 / iOS 18. As a general rule, we always recommend upgrading to the latest version of the SDK to benefit from our latest features and bug fixes.
