### ISSUE TITLE
[Bug]: Build fails with Xcode 15.0.1

### ISSUE THREAD

**Issue by spqw** [braze-inc/braze-swift-sdk#142]
### Platform

iOS

### Platform Version

iOs 17.4

### Braze SDK Version

11.1.1

### Xcode Version

Xcode 15.0.1

### Computer Processor

Apple (M1)

### Repro Rate

100% of the time

### Steps To Reproduce

1. Create a swift package using swift package init
2. Add braze to package dependencies 
3. Try to build for any iOS device

### Expected Behavior

I expect to be able to build using Xcode 15.0.1

### Actual Incorrect Behavior

The build fails

**Comment by jerielng** [comment]
Hey @spqw, to use the Braze Swift SDK, you will need a minimum of Xcode 15.2. Please refer to our [versioning information](https://github.com/braze-inc/braze-swift-sdk?tab=readme-ov-file#version-information) for the full list of requirements. Thanks!
