### ISSUE TITLE
[Bug]:  [iOS] ActivityKit.Activity.pushToStartTokenUpdates.getter

### ISSUE THREAD

**Issue by manikandankumaran** [braze-inc/braze-swift-sdk#143]
### Platform

iOS

### Platform Version

iOS 17.0

### Braze SDK Version

9.0.0

### Xcode Version

15.0.1

### Computer Processor

Apple (M1)

### Repro Rate

100% of the time

### Steps To Reproduce

1. Create a new Xcode project.
2. Navigate to the project directory and add a Podfile using the pod init command.
3. Open the workspace generated by CocoaPods.
4. Add pod 'BrazeKit', '9.0.0' to the Podfile. I have tried upto 11.1.1 Issue not yet fixed
5. Run the app.

### Expected Behavior

Facing this error : 

ld: Undefined symbols:
  static ActivityKit.Activity.pushToStartTokenUpdates.getter : ActivityKit.Activity<A>.PushTokenUpdates, referenced from:
      (1) suspend resume partial function for closure #1 @Sendable () async -> () in BrazeKit.Braze.LiveActivities.registerPushToStart<A where A: ActivityKit.ActivityAttributes, A: BrazeKit.BrazeLiveActivityAttributes>(forType: ActivityKit.Activity<A>.Type, name: Swift.String) -> Swift.Task<(), Swift.Never> in BrazeKit[arm64][2](BrazeKit-arm64-master.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Actual Incorrect Behavior

The app should run, but I'm getting this error when I try to run it in Xcode

**Comment by jacksonemiller** [comment]
Hi there,

Thanks for reaching out. To use our Swift SDK, [you'll need to build your project using Xcode version 15.2 or newer](https://github.com/braze-inc/braze-swift-sdk#version-information). I think that should resolve the issue you're seeing, but feel free to re-open this issue if the problem persists or you have other related questions.

Thanks.
