### ISSUE TITLE
[Bug]: Rate-limiting on dismissal of content cards flow

### ISSUE THREAD

**Issue by Ferdzz** [braze-inc/braze-swift-sdk#148]
### Platform

iOS

### Platform Version

iOS 17+

### Braze SDK Version

11.3.0

### Xcode Version

Xcode 16

### Computer Processor

Apple (M1)

### Repro Rate

100

### Steps To Reproduce

Given the following flow in code, I would expect my content card to disappear from the UI
1. User presses on the close button
2. `card.context?.logDismissed()` is called
3. `braze.contentCards.requestRefresh()` is called
4. We refresh the UI based on the fresh content card list

### Expected Behavior

The card is removed from Braze BE for this user, and the content card list (`braze.contentCards.cards`) is refreshed on the SDK. The refreshed content card list has the dismissed card flagged as `remove == true` 

### Actual Incorrect Behavior

The card Is removed from Braze BE for this user, but the content card list (`braze.contentCards.cards`) is not refreshed on the SDK. Rate limits are hit and this message is logged:
```
Failed to send API request (rate-limited).
- rate-limited until: {
  "shared rate limit" : "2024-11-22T20:10:55Z"
}
```

### Additional Information

We are using custom built UI content cards in our app. The flow works for the first 2-3 cards without problem, but we hit the rate limits after this. 

Is there a problem with the logic of this implementation? It seems that a `contentCards.requestRefresh()` manual refresh is necessary to update Braze's internal list of cards, as calling `logDismissed()` by itself will not update the list of cards. Neither is there update data in the `contentCards.cardsStream`. 

I see two possible solutions to address this:
1. The SDK updates the `removed` property internally when `logDismissed()` is called, bypassing the need for a refresh. This would also be useful for other properties such as `clicked` and `viewed`
2. We keep track of our own list, separate from Braze SDK's and remove it ourselves. Ideally we avoid this solution as it will lead to de-sync between our data and Braze's 

We face the same problem on the Android implementation as well, so this is not platform specific.

Related to https://github.com/braze-inc/braze-react-native-sdk/issues/276

Your help is very much appreciated

**Comment by sircelsius** [comment]
Thank you for reporting @Ferdzz . We are currently investigating this and will reply here!

**Comment by Ferdzz** [comment]
Thanks for the detailed response @jacksonemiller . We will look into having our own internal list tracked. 

We do not use the OOTB UI because the content cards integrate tightly with an already existing feed that we have in the app, so implementing this ourselves was a necessity.

Will look into this further and keep you up to date if we need anything

**Comment by Ferdzz** [comment]
Hello @jacksonemiller. 

As a follow-up question, how does Braze handle removal of content cards following certain actions? For example, if I setup a "Perform custom event" removal event using the dashboard, will a sync of some sort automatically happen when that event is fired? 
<img width="973" alt="image" src="https://github.com/user-attachments/assets/e65d9e39-a949-44b6-831e-8875e1b06c05">
I assume this is evaluated on Braze's backend as opposed to happening on the frontend SDK. How could we keep in our data in sync if a content card has been removed following an automatic removal event? If we need to manually trigger a sync following any potential removal event, we will face rate limiting rather quick. 

Even if we implement our own internally tracked list of cards for when the user manually dismisses a card, we will still face desynchronization if it's been removed by an event. Making us fall out of sync and leaving a card visible in our UI even though it's been automatically removed?

**Comment by jacksonemiller** [comment]
Hi, thanks for the follow-up.

I understand the concern you are referring to in situations where content card syncs are rate limited. This is currently a limitation of our product. We are working on a project internally that could mitigate this limitation sometime in the future. If you feel like this is hampering your user experience, I'd encourage you to file a feature request, support ticket, or talk with your CSM so that we can better understand your use case.
