### ISSUE TITLE
[Bug]: contentCards.subscribeToUpdates not receiving callback

### ISSUE THREAD

**Issue by materik** [braze-inc/braze-swift-sdk#17]
### Platform

iOS

### Platform Version

iOS 16

### Braze SDK Version

5.5.0

### Xcode Version

Xcode 14.0

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

1. Setup a content card campaign in Braze web client
2. Open the app and see a content card be loaded
3. Subscribe to updates with the `contentCards.subscribeToUpdates`
4. Update the content card campaign with new title for the content card and send immediately
5. Not receiving any callback in `subscribeToUpdates` (With a strong reference to cancellable)

### Expected Behavior

Receiving a callback when the campaign is updated in the web client

### Actual Incorrect Behavior

No callback is received from `contentCards.subscribeToUpdates`. Have to restart the app to have the new changes show up.

**Comment by lowip** [comment]
Hi @materik,

Braze only automatically refreshes Content Cards in the following scenarios:
- Session start
- Presenting the Content Cards view controller after [`automaticRefreshTimeout`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazeui/brazecontentcardui/viewcontroller/attributes-swift.struct/automaticrefreshtimeout) has passed.

The Braze SDK will not automatically sync the latest campaigns from the Braze dashboard outside these scenarios. You can always request a refresh via the [`requestRefresh(_:)`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcards-swift.class/requestrefresh(_:)) method.

The behavior you expect is not supported by the SDK, feel free to file a product feedback (more info [here](https://www.braze.com/docs/user_guide/administrative/access_braze/portal/#how-you-can-join-the-conversation))

Thanks,

**Comment by materik** [comment]
Thanks for clarifying @lowip
