### ISSUE TITLE
[Feature]: Missing functionality parity from ABKPushUtils

### ISSUE THREAD

**Issue by jabeattie** [braze-inc/braze-swift-sdk#19]
### What problem are you facing?

We are currently holding off from migrating from appboy-ios-sdk to this new Swift SDk due to some missing features that we currently make use of.

We utilised the `ABKPushUtils` [isUninstallTrackingRemoteNotification](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/include/ABKPushUtils.h#L61) method to abort some of our internal tracking events when receiving remote notifications from Braze to avoid cluttering our own analytics with misleading information.

### Workarounds

It might be possible for us to check if Braze handles the remote push notification and if so abort our internal tracking events at that point, however there is the chance that some of them will have completed by that point.

### Ideal Solution

To have access to similar helper functions in this SDK allowing us to migrate.

Is there any expectation that these functions will be migrated over to this SDK?

**Comment by lowip** [comment]
Hi @jabeattie,

Thank you for opening this issue. We decided to remove all `ABKPushUtils` methods from the Swift SDK as we were struggling to find valid public use-cases for them.

Nonetheless, your use-case seems completely valid and we should be able to add that functionality back in our next release.

To make sure I understand it fully, you want to be able to differentiate between standard notifications (silent or user-visible) and Braze internal notifications that our SDK uses to update its internal state (e.g. uninstall tracking, triggers refresh, geo-fences refresh, etc.)

**Comment by jabeattie** [comment]
Thanks for your reply @lowip 

Yes, that is the exact use case we currently have

**Comment by lowip** [comment]
@jabeattie

We have released [5.6.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.6.0) which includes the new method [`isInternalNotification(_:)`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/notifications-swift.class/isinternalnotification(_:)). This should allow you to filter this type of notifications.

Thanks,
