### ISSUE TITLE
[Feature]: Github Slack integration

### ISSUE THREAD

**Issue by alrocha** [braze-inc/braze-swift-sdk#25]
### What problem are you facing?

Hi folks! 

I am trying to subscribe to releases within slack with the github bot but looks like is not installed, when I run the subscribe command in Slack I get: 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/8307263/200583016-468fb315-6aae-4956-8668-79033a79abf5.png">

### Workarounds

Install the app in the repo just running https://github.com/apps/slack/installations/new 

### Other Information

Thanks in advance! and sorry if feature request is not the right tag, I didn't find any other.

**Comment by lowip** [comment]
Hi @alrocha, thanks for opening this issue.

We'll review adding the Github / Slack integration to our public SDK repositories. In the meantime, you can subscribe to the releases of any Github repository using the [RSS Slack integration](https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack).

Every Github repository vends [multiple RSS feeds](https://vilcins.medium.com/rss-feeds-for-your-github-releases-tags-and-activity-cbda2c51373). You can use `https://github.com/braze-inc/braze-swift-sdk/releases.atom` to follow the Swift SDK releases.

**Comment by alrocha** [comment]
Thanks a lot is already working! :)
