### ISSUE TITLE
[Bug]: Failed to compile if integrated with Cocoapods on M1

### ISSUE THREAD

**Issue by tomisacat** [braze-inc/braze-swift-sdk#28]
### Platform

iOS

### Platform Version

iOS 16.0

### Braze SDK Version

5.6.3

### Xcode Version

Xcode 14.1

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Add `pod 'BrazeKit'` in `Podfile`.
  2. Run `pod install`.
  3. Open xxxx.xcworkspace
  4. Build.

### Expected Behavior

Build succeed.

### Actual Incorrect Behavior
Build succeed on Intel chip Mac, no matter for simulator or real device.

On a M1 chip Mac, it succeed building on `simulator`, but failed building on `real device`, error is `Signing for "BrazeKit-BrazeKit" requires a development team. Select a development team in the Signing & Capabilities editor.` The error is happened on Pod.project -> BrazeKit-BrazeKit target, check the screenshot:

![SCR-20221129-g6o](https://user-images.githubusercontent.com/1179735/204433124-f7cc4f04-09fa-416e-b784-da42dc0e23e6.png)

**Comment by hokstuff** [comment]
Hi @tomisacat,

This error looks to be the same one as in [this issue on the Cocoapods main repo](https://github.com/CocoaPods/CocoaPods/issues/11402) relating to Xcode 14. In the meantime, there currently are workarounds mentioned in that thread (e.g. creating a `post_install` step) that you can follow, and you can also give the issue a 👍 to show signal around it.

Thanks!

**Comment by tomisacat** [comment]
Thanks, the workarounds worked!
