### ISSUE TITLE
[Bug]: InAppMessageView can be dismissed by tap gesture by default

### ISSUE THREAD

**Issue by tomisacat** [braze-inc/braze-swift-sdk#29]
### Platform

iOS

### Platform Version

iOS 16.0

### Braze SDK Version

5.6.3

### Xcode Version

Xcode 14.1

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Configure Braze with In-App Message.
  2. Run the app.

### Expected Behavior

`InAppMessageView` and its subclass can **ONLY** be dismissed by tap `X` or custom button configured in Braze console

### Actual Incorrect Behavior

`InAppMessageView` and its subclass can be dismissed by tapping any point of the view.

**Comment by tomisacat** [comment]
It's cumbersome to inherit `InAppMessageView` and disable `tapGesture` or `pressGesture`. The behavior should be disabled by default as user can dismiss the view by tapping `X`.

**Comment by tomisacat** [comment]
Just found I can implement `func inAppMessage(_ ui: BrazeInAppMessageUI, didPresent message: Braze.InAppMessage, view: InAppMessageView)` and disable this behavior without inheriting `InAppMessageView`.

**Comment by lowip** [comment]
Hi @tomisacat,

Please see our [In-App Message UI Customization](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/in-app-message-customization). 

The section relevant for your use case is _Dismiss modal and full messages on background tap_.
