### ISSUE TITLE
[Bug]: removed and viewed properties don't persist through sessions

### ISSUE THREAD

**Issue by OmarPedraza** [braze-inc/braze-swift-sdk#30]
### Platform

iOS

### Platform Version

iOS 16.1

### Braze SDK Version

5.6.3

### Xcode Version

14.1

### Computer Processor

Apple (M1)

### Repro Rate

100% of the time

### Steps To Reproduce

1. Fetch content cards from server
2. Change their `removed` and/or `viewed` values
3. Fetch content cards from server again

### Expected Behavior

`removed` and `viewed` values should be stored in the server in order to persist between sessions

### Actual Incorrect Behavior

Content cards always return `false` for both `removed` and `viewed`, without taking into account the modifications done by the user.

**Comment by jerielng** [comment]
Hi @OmarPedraza, thanks for reaching out! Each content card has a [Context](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcardraw/context-swift.class) object that allows you to perform actions like [`logImpression()`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcardraw/context-swift.class/logimpression()) to mark a card as viewed and [`logDismissed()`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcardraw/context-swift.class/logdismissed()/) to mark a card as removed.

Additionally, you can also call [`requestImmediateDataFlush()`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/requestimmediatedataflush()) to ensure that the server immediately receives the latest changes.

Let me know if that helps solve your issue!

**Comment by OmarPedraza** [comment]
Hi @jerielng,
thanks for your response.

We're now using those methods and content cards finally maintain their status between sessions but we've realized something else: even if we call `requestImmediateDataFlush()` after `logDismissed()` or `logImpression()`, changes are not automatically applied and `removed` and `viewed` are not updated in `braze.contentCards.cards` array.

Are you updating the local status of the content card or that's something that should be on our side?

**Comment by jerielng** [comment]
Hey @OmarPedraza, logging an impression or removal will only update the SDK's internal state, which gets published to the server the next time data is flushed. These actions do not directly modify the `removed` or `viewed` state of your `braze.contentCards.cards`.

To update the local state of your `braze.contentCards.cards`, you can refresh your cards from the server by calling [`requestRefresh()`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcards-swift.class/requestrefresh(_:)).

Depending on what you're trying to accomplish, you can also update your UI manually to reflect your card changes as a follow-up step after calling `logDismissed()` or `logImpression()`. There are examples in our [`BrazeUI` module](https://github.com/braze-inc/braze-swift-sdk/blob/main/Sources/BrazeUI/ContentCardUI/ContentCardUIViewController.swift#L444-L450).

**Comment by OmarPedraza** [comment]
Hi @jerielng,
thanks for the feedback.

We've finally decided to make a `requestRefresh()` call after logging impression and removal and it works like a charm.

Thanks again for the help!
