### ISSUE TITLE
[Bug]: Content card doesn't clear out after expiration

### ISSUE THREAD

**Issue by louisebehrenfors-s** [braze-inc/braze-swift-sdk#37]
### Platform

iOS

### Platform Version

iOS 16.1.1

### Braze SDK Version

5.9.0

### Xcode Version

Xcode 14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Set up a content card campaign with an expiration date.
  2. Launch the campaign and wait for the card to hit the expiration time.
  3. The expired card remains in the list, pull to refresh/relaunching does not clear out the card 
  4. We are using the ContentCardsUI.ViewController with no customization. 

### Expected Behavior

The expired cards should no longer be visible.

### Actual Incorrect Behavior

The expired cards are still there.

### Additional Information

We are using the ContentCardsUI.ViewController with no customization. 
The test content cards and campaign card does not go away after they have expired.
Pull to refresh does not help.

**Comment by lowip** [comment]
Hi @louisebehrenfors-s,

Thank you for opening this issue.
We are able to reproduce this issue and are working on a fix. We will update this thread once the fix is released.

**Comment by hokstuff** [comment]
Hi @louisebehrenfors-s,

We have released [version 5.9.1](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.9.1) which fixes this issue - let us know if you run into any problems. Thanks!

**Comment by louisebehrenfors-s** [comment]
Hi again! @hokstuff Thanks for the quick fix. 
I have just one more question, when doing the `contentCards.requestRefresh`, is it expected that it returns cards that have expired? However when I tested previously I saw it disappear once it hit its expiration time (when using non-custom UI). But if we wanna do a custom solution, we need to handle the expiration check ourselves?

**Comment by louisebehrenfors-s** [comment]
Hello again! Thanks for the quick fix 💃 @hokstuff @lowip 
When we send the test content card for preview, they disappear right after they have been viewed. Is that expected? I expected them to be around for 5 minutes.

**Comment by lowip** [comment]
Hi @louisebehrenfors-s,

We're able to reproduce the issue and are tracking it internally. We'll update here once the fix is available.

**Comment by lowip** [comment]
Hi @louisebehrenfors-s,

This issue has been fixed in [`5.10.0`](https://github.com/braze-inc/braze-swift-sdk/blob/main/CHANGELOG.md#5100).

Best,
