### ISSUE TITLE
[Feature]: ABKCard class - a lot of methods UnImplement

### ISSUE THREAD

**Issue by LucioPham** [braze-inc/braze-swift-sdk#38]
### Platform

iOS

### Platform Version

iOS 16.1.1

### Braze SDK Version

5.9.1

### Xcode Version

Xcode 14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

We are using a lot of methods to initialize an object that is inherited from `ABKCard` class like `ABKCaptionedImageCard`.

But after upgrading and integrating from Appboy-SDK to the new Braze Swift SDK we got a lot of logs that mention a lot of methods we are using are `UnImplemented` as a log below.

`[BrazeKitCompat] 'ABKCaptionedImageCard.copyWithZone:' is not implemented.`

Including the following methods:

> - (nullable instancetype)initWithCoder:(nonnull NSCoder *)coder
> - (void)encodeWithCoder:(nonnull NSCoder *)coder
> - (NSData *)serializeToData
> + (ABKCard *)deserializeCardFromDictionary:(NSDictionary *)cardDictionary

### Expected Behavior

Supporting back those methods from `ABKCard` class.

### Actual Incorrect Behavior

Not supporting those methods from `ABKCard` class.

### Verbose Logs

```shell
[BrazeKitCompat] 'ABKCaptionedImageCard.copyWithZone:' is not implemented.
```

**Comment by LucioPham** [comment]
Hi @lowip , sorry for bothering you but could you help me with this issue, we are using Braze service and are really in rush to release a new version.

**Comment by hokstuff** [comment]
I am closing out this issue since we have an alternative implementation. If you have any other comments, feel free to reach out to support@braze.com and submit a product request.

Thanks!
