### ISSUE TITLE
[Bug]: shouldOpenURL delegate method not being called

### ISSUE THREAD

**Issue by danielocampo2** [braze-inc/braze-swift-sdk#39]
### Platform

iOS

### Platform Version

14.6

### Braze SDK Version

5.9.0

### Xcode Version

14.0.1

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Extend `BrazeDelegate` in `AppDelegate.swift`.
  2. Set `braze.delegate = self` when initializing Braze instance.
  3. Implement `func braze(_ braze: BrazeKit.Braze, shouldOpenURL context: BrazeKit.Braze.URLContext) -> Bool`
  4. Run the app.
  5. Send notification to this user containing a deeplink to the app. (Deep Link into Application setting)
  6. Tap on the notification so the app is opened.

### Expected Behavior

`braze(_ braze: BrazeKit.Braze, shouldOpenURL context: BrazeKit.Braze.URLContext)` is called in delegate with the deeplink information.

### Actual Incorrect Behavior

`braze(_ braze: BrazeKit.Braze, shouldOpenURL context: BrazeKit.Braze.URLContext)` is never called.

### Additional Information

We are using the latest flutter plugin (braze-flutter-sdk), that needs native implementation.

This was working properly in `braze-flutter-sdk 2.6.1` which used [Braze iOS SDK 4.5.1](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#451).

This is our current configuration in AppDelegate.swift:

```
func configureBraze() {
        let brazeKey = Bundle.main.infoDictionary?["BrazeSdkKey"] as! String
        let brazeEndpoint = Bundle.main.infoDictionary?["BrazeEndpoint"] as! String
        let configuration = Braze.Configuration(
          apiKey: brazeKey,
          endpoint: brazeEndpoint
        )
        configuration.triggerMinimumTimeInterval = 0
        configuration.logger.level = .debug

        let braze = Braze(configuration: configuration)
        braze.delegate = self
        braze.enabled = true

        AppDelegate.braze = braze
}

func braze(_ braze: BrazeKit.Braze, shouldOpenURL context: BrazeKit.Braze.URLContext) -> Bool {
      let deeplink = context.url
      // Handle deeplink
      return false
}
```

**Comment by lowip** [comment]
Hi @danielocampo2,

Thank you for reporting this issue. Can you confirm the following:
- `configureBraze()` is called in `application(_:didFinishLaunchingWithOptions:)` (to ensure that Braze is started when receiving the notification)
- Are you using the `setSdkAuthenticationDelegate` flutter method anywhere in your application?

**Comment by danielocampo2** [comment]
Hi @lowip,

1) Yes, `configureBraze()` is called in `application(_:didFinishLaunchingWithOptions:)`.
2) No, we are not using that method. Would that be useful in any way?

Thanks for your answer.

**Comment by lowip** [comment]
> 1. Yes, configureBraze() is called in application(_:didFinishLaunchingWithOptions:).

Your integration looks good.

> 2. No, we are not using that method. Would that be useful in any way?

This method overrides the `braze.delegate`, we'll refactor it to avoid that behavior. You shouldn't need to use it unless integrating our [SDK Authentication](https://www.braze.com/docs/developer_guide/platform_wide/sdk_authentication/) feature.

---

For the next steps, could you please send to support@braze.com:
- The link to your push notification campaign dashboard page
- Logs with the `.debug` level of the interaction with the push notification

This will help us to reproduce locally the issue.

**Comment by danielocampo2** [comment]
Thanks @lowip, I have already sent the requested information. Case Number: 00134624.

**Comment by hokstuff** [comment]
Hi @danielocampo2, are you still experiencing this issue?

**Comment by ofournier-nuglif** [comment]
Hi can you please look into this issue, we are waiting on it to migrate the SDK, thanks !

**Comment by danielocampo2** [comment]
We are still waiting for an answer from support. They said the issue was
complex so it is taking time to resolve.

We won't spent more time on this until we get an answer from them.

Anything you can do to speed up the process?

Thanks.

**Comment by hokstuff** [comment]
Closing this public issue based on the thread on the Support channels. For any additional follow-ups, feel free to send more info to our Support team - thanks!
