### ISSUE TITLE
[Feature]: Missing documentation for Content Cards as supplemental content

### ISSUE THREAD

**Issue by adrienyvon699** [braze-inc/braze-swift-sdk#41]
### What problem are you facing?

I want to implement Content Cards as supplemental content, basically add one content card where I need.
On your website [this](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/content_cards/implementation_guide/#content-cards-as-supplemental-content) is the only doc that I've found and it's pretty vague with no steps to implement.

Can you please produce the doc or redirect me to an example?

### Workarounds

N/A

### Ideal Solution

A doc that explains how we can get the card from Braze and display it in our own collectionView/tableView

**Comment by lowip** [comment]
Hi @adrienyvon699,

You should find what you're looking for in the [`ContentCards-Custom-UI`](https://github.com/braze-inc/braze-swift-sdk/tree/main/Examples) example app.

All Content Cards related method are available in the [`Braze.ContentCards`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcards-swift.class) module. This module exposes the [`cards`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcards-swift.class/cards) property, which contains all the current Content Cards.

You can access the module from your Braze instance, e.g. `AppDelegate.braze?.contentCards.cards`.

Let us know if you need more information, we are in the process of updating the documentation on `braze.com`. In the meantime, we recommend referring to the [SDK documentation](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit).

**Comment by adrienyvon699** [comment]
OK thank you I was able to find the example and it's helped me understand this better.
So basically we can do whatever we want with the data coming from the cards via `AppDelegate.braze?.contentCards.cards`.

Let me know when you add this to the [SDK documentation](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit) because again as of now I don't see it and it would be great for everyone to have it!

Thank you!

**Comment by lowip** [comment]
> OK thank you I was able to find the example and it's helped me understand this better. So basically we can do whatever we want with the data coming from the cards via `AppDelegate.braze?.contentCards.cards`.

Yes, you should also check out the [`subscribeToUpdates(_:)`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/contentcards-swift.class/subscribetoupdates(_:)) of the same module to be notified of new Content Cards.

> Let me know when you add this to the [SDK documentation](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit) because again as of now I don't see it and it would be great for everyone to have it!

Will do/
