### ISSUE TITLE
[Build Settings]: BrazeKit.framework doesn't contain bitcode.

### ISSUE THREAD

**Issue by wiosm** [braze-inc/braze-swift-sdk#45]
### Platform

iOS

### Platform Version

Any iOS

### Braze SDK Version

5.10.1

### Xcode Version

14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

  1. Archive project with bitcode enable
  2. Error from console log: BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/BrazeKit/BrazeKit.framework/BrazeKit(BrazeKit-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE)

### Expected Behavior

BrazeKit.framework should enable bitcode

### Actual Incorrect Behavior

BrazeKit.framework doesn't enable  bitcode

### Verbose Logs

```shell
BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/BrazeKit/BrazeKit.framework/BrazeKit(BrazeKit-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE)
```

**Comment by lowip** [comment]
Hi @wiosm,

As stated per Xcode 14 release notes:

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
>
> Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols can only be downloaded from App Store Connect / TestFlight for existing bitcode submissions and are no longer available for submissions made with Xcode 14. (86118779)

We intend to follow Apple's guidelines. Are there any reason mandating the use of bitcode in your organization?

**Comment by wiosm** [comment]
So we are ok with this. Actually our project still using bitcode due to internal reason. We will find the way to by pass this issue. Thanks for your support.
