### ISSUE TITLE
[Feature]: BrazeKit - Support for Xcode 14.3 Beta

### ISSUE THREAD

**Issue by patrickniepel** [braze-inc/braze-swift-sdk#46]
### What problem are you facing?

We are using SPM to integrate `BrazeKit` into our project. Since `BrazeKit` is defined as a binary target we cannot use it with Xcode 14.3 due to incompatible compiler versions.

```
Failed to build module 'BrazeKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.117.11 clang-1403.0.22.8.60)'). Please select a toolchain which matches the SDK.
```

### Workarounds

Continue using Xcode 14.2

### Ideal Solution

Could you give us an ETA of when a compatible version of the SDK will be released?
Would a beta branch be a viable option for you?

Thanks in advance.

**Comment by hokstuff** [comment]
Hi @patrickniepel,

I found [this thread with a similar error](https://stackoverflow.com/a/58656323) containing steps to resolve it. Can you try updating your project's settings with the suggestion in the comment? Here is some more [info on the build setting](https://www.swift.org/blog/library-evolution/) in the Swift docs.

Thanks!

**Comment by EmDee** [comment]
> Hi @patrickniepel,
> 
> I found [this thread with a similar error](https://stackoverflow.com/a/58656323) containing steps to resolve it. Can you try updating your project's settings with the suggestion in the comment? Here is some more [info on the build setting](https://www.swift.org/blog/library-evolution/) in the Swift docs.
> 
> Thanks!

@hokstuff The `BUILD_LIBRARY_FOR_DISTRIBUTION` is a flag the library, Braze, has to set in this case. This is can't be solved by the client.

**Comment by hokstuff** [comment]
@EmDee Thanks for raising that!

We actually responded to the original post in our Support channel and have verified that `BUILD_LIBRARY_FOR_DISTRIBUTION` is set in our SDK. For visibility - we are currently investigating on a solution that will allow for support with Xcode 14.3 and will keep this thread updated once we determine the best next steps.

Thanks!

**Comment by jerielng** [comment]
Hi @EmDee, we've released a beta-compatible version of our `5.11.0` SDK [here](https://github.com/braze-inc/braze-swift-sdk-xcode-14-3-preview). There are some constraints called out in the README, but these binaries should be compatible with the newest Xcode 14.3 beta.

Please let us know if this resolves your issue!

**Comment by EmDee** [comment]
@jerielng Thank you! We will give this a spin in the upcoming days. Seeing how Xcode 14.3 is still in beta, we won't fully transition until the stable release anyway, but good to test the dependencies out beforehand.

**Comment by patrickniepel** [comment]
@jerielng Thanks for the update. The README is mentioning a bug that prevents support for iOS 11 and 12. Out of curiosity, what kind of bug were you facing?

**Comment by jerielng** [comment]
@patrickniepel With our binaries, it seems that this version of Xcode generates a dependency on [`MainActor`](https://developer.apple.com/documentation/swift/mainactor), which is only available on iOS 13+.

This is documented in other issues [here](https://github.com/facebook/facebook-ios-sdk/issues/2181) and [here](https://stackoverflow.com/questions/75514974/heremaps-ios-sdk-v4-13-3-not-compiling-with-xcode-14-3).

Since the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes) for this version indicate support for iOS 11+, we would consider this a bug.

**Comment by hokstuff** [comment]
I'm closing out this issue since we have addressed the original request and have created a separate repo that is compatible with Xcode 14.3 beta, [mentioned here](https://github.com/braze-inc/braze-swift-sdk/issues/46#issuecomment-1450173087).

Thanks!

**Comment by jerielng** [comment]
Hey @holyavkin, thanks for raising this. Since you are using CocoaPods, can you try importing our 14.3 beta pods using the `:podspec` directive and with the URL below instead of the `:git` directive?

```
pod 'BrazeKit', :podspec => 'https://raw.githubusercontent.com/braze-inc/braze-swift-sdk-xcode-14-3-preview/{braze-sdk-version}/BrazeKit.podspec'
pod 'BrazeUI', :podspec => 'https://raw.githubusercontent.com/braze-inc/braze-swift-sdk-xcode-14-3-preview/{braze-sdk-version}/BrazeUI.podspec'
pod 'BrazeKitCompat', :podspec => 'https://raw.githubusercontent.com/braze-inc/braze-swift-sdk-xcode-14-3-preview/{braze-sdk-version}/BrazeKitCompat.podspec'
pod 'BrazeUICompat', :podspec => 'https://raw.githubusercontent.com/braze-inc/braze-swift-sdk-xcode-14-3-preview/{braze-sdk-version}/BrazeUICompat.podspec'
```

We'll be updating the README in the next release.

**Comment by EmDee** [comment]
@jerielng Did you dive into the problem why `BUILD_LIBRARY_FOR_DISTRIBUTION` seemingly has no effect for your library? This seems strange to me why the flag doesn't work for your binaries.

**Comment by holyavkin** [comment]
@jerielng, it does work this way. Thank you!

**Comment by lowip** [comment]
Hi everyone, please see [here](https://github.com/braze-inc/braze-swift-sdk/issues/52) for an update regarding support for Xcode 14.3 RC.

**Comment by EmDee** [comment]
> Hi again! You can use the latest Xcode (14.3 Release Candidate 2 - 14E222b) with our main repository: https://github.com/braze-inc/braze-swift-sdk
> 
> 
> 
> We have archived the [preview repository](https://github.com/braze-inc/braze-swift-sdk-xcode-14-3-preview). Please revert your integration to use the main repository.
> 
> 
> 
> 

That was fast!

Just got read the RC 2 release notes and wanted to report here.

We'll give the latest version a go this week.
