### ISSUE TITLE
[Bug]: Content card - crash in updateImage

### ISSUE THREAD

**Issue by louisebehrenfors-s** [braze-inc/braze-swift-sdk#47]
### Platform

iOS

### Platform Version

iOS 16

### Braze SDK Version

5.9

### Xcode Version

Xcode 14.2

### Computer Processor

Apple (M1)

### Repro Rate

-

### Steps To Reproduce

Hello! 

Our Crashlytics has detected some crashes regarding the update image cells for content cards. 

<img width="377" alt="crashlytics-BrazeContentCardUI.ViewController.updateImageCell" src="https://user-images.githubusercontent.com/69787983/222084107-d47c9fc3-034f-486a-85b5-f3f819509193.png">

Let me know if there is anything else you need. I added the crashlytics-logs below.

### Expected Behavior

Expected no crashing around image loading. 

### Actual Incorrect Behavior

It crashed.

### Verbose Logs

```shell
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x9e88 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  Foundation                     0x545b4c _userInfoForFileAndLine
3  CoreAutoLayout                 0x1488 -[NSLayoutConstraint _setMultiplier:]
4  CoreAutoLayout                 0xb5b4 +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]
5  Redacted                       0x5f4f1c @nonobjc NSLayoutConstraint.__allocating_init(item:attribute:relatedBy:toItem:attribute:multiplier:constant:) (<compiler-generated>)
6  Redacted                       0x5ac37c specialized static Constraints.add<A, B, C, D>(::constant:multiplier:relation:) + 566 (Align.swift:566)
7  Redacted                       0x5ab398 AsyncImageView.updateAspectRatio() (<compiler-generated>)
8  Redacted                       0x5ab8a4 AsyncImageView.updateImage() + 56 (AsyncImageView.swift:56)
9  Redacted                       0x5a3410 closure #1 in BrazeContentCardUI.ViewController.updateImageCell(cell:imageLoad:) + 76 (AsyncImageView.swift:76)
10 Redacted                       0x5b5ebc thunk for @callee_guaranteed () -> () (<compiler-generated>)
11 Redacted                       0x5b5edc thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
12 UIKitCore                      0x31564 +[UIView(Animation) performWithoutAnimation:]
13 Redacted                       0x5a30ac BrazeContentCardUI.ViewController.updateImageCell(card:imageLoad:) (<compiler-generated>)
14 Redacted                       0x5a2a7c closure #1 in load #1 (_:) in BrazeContentCardUI.ViewController.loadImage(card:retry:) + 558 (ContentCardUIViewController.swift:558)
15 Redacted                       0x8ec734 partial apply for closure #1 in closure #1 in closure #6 in Braze.ContentCardRaw.Context.init(card:viewStore:assets:)
16 Redacted                       0x8e8110 thunk for @escaping @callee_guaranteed () -> ()
17 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release
18 libdispatch.dylib              0x3fdc _dispatch_client_callout
19 libdispatch.dylib              0x127f4 _dispatch_main_queue_drain
20 libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF
21 CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
22 CoreFoundation                 0x7c058 __CFRunLoopRun
23 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific
24 GraphicsServices               0x1368 GSEventRunModal
25 UIKitCore                      0x3a23d0 -[UIApplication _run]
26 UIKitCore                      0x3a2034 UIApplicationMain
27 Redacted                       0x3e358 main (<compiler-generated>)
28 ???                            0x1ac7a4960 (Missing)'
```

**Comment by jerielng** [comment]
Hi @louisebehrenfors-s thanks for the information in the logs. We'll look into the issue from our end and let you know what we find. In the meantime, could you provide some additional details around your usage of Content Cards?

* Could you describe how you're using Content Cards UI in your app?
* Are there certain example images that you're using for your Content Card cells?
* Are you able to reproduce this in your own development environment?
* Are there any trends you're observing in the version of iOS that this crash is occurring on in your Crashlytics logs, or is this crash occurring for all users across the board?

**Comment by lowip** [comment]
Hi @louisebehrenfors-s,

Is the issue still occurring on your side?

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. If you are still experiencing issues, please attach the information requested [here](https://github.com/braze-inc/braze-swift-sdk/issues/47#issuecomment-1450291336) in an email to support@braze.com so our Support team can investigate further. Thanks!
