### ISSUE TITLE
[Feature]: cocoapods support

### ISSUE THREAD

**Issue by Wooder** [braze-inc/braze-swift-sdk#5]
### What problem are you facing?

Many projects still use cocoapods as dependency manager.
Supporting cocoapods (in addition to SPM) would increase SDK adoption.

### Workarounds

No workarounds.

**Comment by Bucimis** [comment]
@Wooder We don't have an exact timeline to share but Cocoapods support is on our roadmap/in development :)

**Comment by lowip** [comment]
Hi @Wooder, we have released [5.1.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.1.0) with support for CocoaPods. You can check out the example CocoaPods integration in our [_Examples_](https://github.com/braze-inc/braze-swift-sdk/tree/5.1.0/Examples) directory.

**Comment by Wooder** [comment]
Great news! Thanks 👍
