### ISSUE TITLE
[Bug]: In App Message clickAction doesn't handle Deeplink nor opens URL into WebView

### ISSUE THREAD

**Issue by mperelloblinkist** [braze-inc/braze-swift-sdk#59]
### Platform

iOS

### Platform Version

iOS 16.4.1

### Braze SDK Version

5.13.0

### Xcode Version

Xcode 14.3

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Send a test for an In-App Message with an In-App Deeplink.
  2. Tap on the notification -> App is opened and In-App Message is displayed
  3. Tap on the CTA

### Expected Behavior

Deeplink is handled and In-App Message is dismissed

### Actual Incorrect Behavior

In-App Message is dismissed.

Digging into the code I have confirmed:
1. `BrazeInAppMessageUIDelegate inAppMessage shouldProcess clickAction` is called and returns true
2. `InAppMessageView.process(clickAction..` is called and makes it all the way to the bottom where this is called: `context.processClickAction(clickAction)`; however I cannot debug into this which is where I assume the problem lies.
3. `BrazeDelegate.shouldOpenURL` is not being called

### Additional Information

ContentCards In-App Deeplinks and WebView work as expected.

**Comment by cbowns** [comment]
Hi @mperelloblinkist, thanks for the detailed bug report! Can you write in to support@braze.com, reference this issue, and include the campaign or deeplink(s) you're trying? We can continue working with you there to avoid having to share those details here in public.

**Comment by hokstuff** [comment]
@mperelloblinkist Are you still experiencing this issue, or have you been able to resolve it by contacting our Support team, as mentioned above?

**Comment by mperelloblinkist** [comment]
Yes, it has been resolved with the latest release 6.0.0
