### ISSUE TITLE
[Feature]: Update push subscription state

### ISSUE THREAD

**Issue by bswaidner** [braze-inc/braze-swift-sdk#6]
### What problem are you facing?

The previous SDK allows a simple interface for subscribing / unsubscribing to push notifications. https://www.braze.com/docs/user_guide/message_building_by_channel/push/users_and_subscriptions/#push-sub-states

### Workarounds

Use the rest api to update subscription state

### Ideal Solution

Two functions `braze.notifications.unsubscribe()` & `braze.notifications.subscribe()` or a single function that allows a state to be passed

### Other Information

I tried enabling / disabling the entire braze instance (i.e. `braze.enabled = false`) but notifications still come through

**Comment by Bucimis** [comment]
@bswaidner try using `public func set(pushNotificationSubscriptionState: Braze.User.SubscriptionState)` on the Braze User class

**Comment by bswaidner** [comment]
@Bucimis Awesome thanks for the quick response - thought I'd looked everywhere. Works as expected 👍
