### ISSUE TITLE
[Feature]: Support both static & dynamic frameworks via Package managers

### ISSUE THREAD

**Issue by shahzadmajeed** [braze-inc/braze-swift-sdk#61]
### What problem are you facing?

Hi. 

Currently XCFrameworks include statically built products/libraries but sometime we have to rely on dynamic products/libraries i.e., when using same dependency in multiple targets. This is to avoid copying symbols from static binaries into multiple targets which results into duplicate symbols errors.

Could you please include both static & dynamic binaries so that developers have a choice?

Thank you

### Workarounds

N/A

### Ideal Solution

Mentioned in the problem above but ideally we should add both static and dynamic libraries in the XCFramework. To keep the backward compatibility you can keep existing products as is but add new ones with `Dynamic` appended i.e., `BrazeKitDynamic.dylib` etc.

**Comment by hokstuff** [comment]
Hi @shahzadmajeed,

If you download `braze-swift-sdk-prebuilt.zip` from the relevant [release](https://github.com/braze-inc/braze-swift-sdk/releases/), this contains both dynamic and static xcframeworks. Let us know if this fulfills your use case!

Also note that in [5.14.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.14.0) there was an update the BrazeUI framework.

Thanks!

**Comment by hokstuff** [comment]
Thanks for describing your use case in detail. Currently, we just provide the functionality to choose between static and dynamic via the assets directly, and we do not yet support dynamic frameworks when using SPM or Cocoapods. We have filed this feature request internally and will be in touch if we have further updates - thank you!

**Comment by lowip** [comment]
Hi @shahzadmajeed,

With our 7.4.0 release, we've added two new repositories offering our libraries as either static or dynamic XCFrameworks. Please refer to [this table](https://github.com/braze-inc/braze-swift-sdk#alternative-repositories) in the README and to the [7.4.0 entry](https://github.com/braze-inc/braze-swift-sdk/blob/main/CHANGELOG.md#740) in the CHANGELOG.

Thanks,
