### ISSUE TITLE
[Feature]: Alternative to AppBoyProvider.isAppboyRemoteNotification

### ISSUE THREAD

**Issue by remarcus** [braze-inc/braze-swift-sdk#66]
### What problem are you facing?

Hey, we're migrating from Appboy to Swift SDK.

In [userNotificationCenter(_:willPresent:withCompletionHandler:)](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter) we had check for `AppBoyProvider.isAppboyRemoteNotification` to provide required presentation options for foreground Braze push notifications.

I don't see alternative to this method and `Braze.Notifications.isInternalNotification(userInfo:)` returns false as this is not an internal push.

We handle our internal push notifications inside our app and show a custom UI, so now there's no way to differentiate.

Could you assist me with that?

### Workarounds

-

**Comment by jerielng** [comment]
Hey @remarcus, one thing to note is that `isAppboyRemoteNotification` is not equivalent to `isInternalNotification` in the Swift SDK. `isAppboyInternalRemoteNotification` in AppboyKit would be the equivalent to `Braze.Notifications.isInternalNotification`, so the behavior you observe may be different.

That being said, `isAppboyRemoteNotification` has been removed to simplify the Notifications interface. If you would like to continue checking if a notification is from Braze, you can check for the presence of a valid object with the key `"ab"` in the payload of `notification.request.content.userInfo`.

Alternatively, we have also provided some new ways using boolean return values to verify that a push was handled by Braze:
* [handleBackgroundNotification(userInfo:fetchCompletionHandler:)](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/notifications-swift.class/handlebackgroundnotification(userinfo:fetchcompletionhandler:)/)
* [handleUserNotification(response:withCompletionHandler:)](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/notifications-swift.class/handleusernotification(response:withcompletionhandler:))

If you'd like to learn more about the implementation and usage of these methods, you can refer to our push integration tutorial [here](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b1-standard-push-notifications).

**Comment by remarcus** [comment]
Hey @jerielng,

Thanks for a quick response. I understand that the methods are not the same.

What would be the valid object definition for "ab"? That it contains object with "c" as a key and some UUID? Maybe checking for "ab" existence will be enough for us.

**Comment by remarcus** [comment]
Thanks for the help! Closing the issue 😃
