### ISSUE TITLE
[Feature]: Improve migration documentation

### ISSUE THREAD

**Issue by tsal** [braze-inc/braze-swift-sdk#70]
### What problem are you facing?

While migrating our iOS app, there are two paths provided, and it is implied the second path needs the first path / needs some parts of it. That isn't clear. In addition, "In-App Messaging UI" probably needs to spell out that this is for _the entire feature_ because with the notice underneath it, it looks like it's for _setting up the UI_, which we don't customize.

### Workarounds

Reading 3 different documents to get the correct and concise answer.

### Ideal Solution

- Updating the two migration paths to completely decouple them, even if the steps are the same.
- Updating the "In-App Messaging UI" heading to be "In-App Messaging" and provide more detail about what is needed -- or just provide the _single line of code_ that is needed in the most basic case.

### Other Information

Don't take this request badly - the documentation was _really good_, compared to other "integration" docs from analytics providers, just these two minor issues that caused more confusion than necessary.

**Comment by hokstuff** [comment]
Hi @tsal,

Thanks for the pointers in our documentation.

> Updating the two migration paths to completely decouple them, even if the steps are the same.

I believe you are referencing how [steps 1-2 in this section](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide#:~:text=To%20perform%20the,KitCompat%3A) are a short rewording of Scenario 1's section? We'll look into either copy-pasting the relevant content or else an explicit "follow steps X-Y in `Scenario 1`" to make sure people first read through all of Scenario 1 prior to starting Scenario 2.

> Updating the "In-App Messaging UI" heading to be "In-App Messaging" and provide more detail about what is needed -- or just provide the single line of code that is needed in the most basic case.

Are you referencing [this section](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/#:~:text=Registering%20the%20In%2DApp%20Message%20UI%20is%20now%20a%20manual%20step.%20To%20use%20the%20Braze%20In%2DApp%20Message%20UI%2C%20follow%20our%20tutorial%20In%2DApp%20Message%20UI.) of our migration docs? The highlighted text talks more generally about the In-App Messaging UI itself, and the [`Tip`](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide#:~:text=If%20you%20were%20previously%20customizing%20the%20appearance%20or%20behavior%20of%20the%20Appboy%20In%2DApp%20Message%20UI) below discusses extra work needed when performing customization.

I get how it can be confusing, and I think moving the `Tip` below the `Main API changes` section should be sufficient. This way, all the content necessary for using In-App Message UI (both default and customized) should be together on the top, and only the customization steps will be below it.

Best,
Daniel

**Comment by tsal** [comment]
Thanks! I think explicitly stating the steps need to be taken would help! And also think moving the `Tip` section would definitely eliminate any confusion there, too! Thanks!

**Comment by lowip** [comment]
Hi @tsal,

The documentation has been updated in our last release, thanks again for the feedback!
