### ISSUE TITLE
[Bug]: Images in ABKInAppMessageWindow Dont Scale Correctly

### ISSUE THREAD

**Issue by virbedi** [braze-inc/braze-swift-sdk#72]
### Platform

iOS

### Platform Version

iOS 16.2

### Braze SDK Version

6.3.1

### Xcode Version

Xcode 14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

  1.  Replace Appboy-iOS-SDK with BrazeKitCompat 6.3.1 and BrazeUICompat 6.3.1 in podfile and import statements across the app
  2. View a full screen modal using the `ABKInAppMessageWindow`.

### Expected Behavior

The header image at the top of the modal should scale to fit the entire width of the modal.

### Actual Incorrect Behavior

The Image is scaled differently and display in the center instead of the entire width of the modal. 
Before and After images when using Appboy-iOS-SDK', '~> 4.1.0' vs BrazeKitCompat 6.3.1
<img width="1149" alt="Screenshot 2023-07-19 at 4 19 58 PM" src="https://github.com/braze-inc/braze-swift-sdk/assets/43729852/9e0370f9-0f2e-4d78-beb0-62677d87e280">

### Additional Information

We are trying to migrate from the older AppBoy SDK to the new BrazeKit SDK and would like to use the Compat libraries before we migrate fully to the new SDK. 

The images as part of our UI are not scaling as they were before. 
The only changes made were to the import statements and Podfile as per the [Migration Guide](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/)

**Comment by lowip** [comment]
Hi @virbedi,

Thank you for opening this issue. Could you upload the specific image on this thread? We need to make sure we reproduce in the same conditions.

**Comment by virbedi** [comment]
<img src="https://braze-images.com/appboy/communication/assets/image_assets/images/619c4b7c63c2066f7ecaf6c3/original.png?1637632892" width="230"/>

Here's the image that is uploaded to the Braze Dashboard.

**Comment by lowip** [comment]
@virbedi,

Thank you for providing this asset. We've identified the issue and are reviewing a fix that should be part of the next release.
In the meantime, you can pin your dependency `5.14.0` which does not suffer from that issue.

We'll update here once the fix is available.

**Comment by virbedi** [comment]
Thanks for the quick response. I'll give 5.14.0 a try in the mean time.

**Comment by lowip** [comment]
Hi @virbedi,

We have released [`6.4.0`](https://github.com/braze-inc/braze-swift-sdk/releases/tag/6.4.0) which includes the fix for this issue.

Best,
