### ISSUE TITLE
[Bug]: Notification Content Extension can not find BrazePushStory module 

### ISSUE THREAD

**Issue by ehuangmove** [braze-inc/braze-swift-sdk#75]
### Platform

iOS

### Platform Version

iOS 16

### Braze SDK Version

6.5.0

### Xcode Version

14.2

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

I was following this guide: https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b3-push-stories/
Example:
  1. Add the BrazeSDK package to main target by only selecting `BrazeKit`
  2. Create Notification Content Extension 
  3. Look for BrazePushStory module in available frameworks

### Expected Behavior

https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b3-push-stories/

Refer to Step 3

### Actual Incorrect Behavior

https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b3-push-stories/

Can not get past Step 3

### Additional Information

<img width="1728" alt="Screen Shot 2023-08-16 at 3 59 29 PM" src="https://github.com/braze-inc/braze-swift-sdk/assets/105666502/c0712d52-238c-48d0-a890-50489955b00a">

**Comment by jerielng** [comment]
Hi @ehuangmove, we'll take a deeper look into why certain packages are not showing up on the list. In the meantime, if you happen to have a copy of Xcode 14.3 installed, I was able to link `BrazePushStory` using 14.3 and then return back to build on 14.2. It's possible that it may be an issue with SPM on that version of Xcode.

**Comment by ehuangmove** [comment]
@jerielng Thanks! We are able to resolve this issue with a new Xcode

**Comment by jerielng** [comment]
Thanks for the update @ehuangmove! Taking a deeper look, it looks to be an issue specific to versions of Xcode <= 14.2. Using higher versions from 14.3+ should work fine. I'll go ahead and close out the issue, but let us know if you have any further questions!
