### ISSUE TITLE
[Bug]: Compiler warning when importing `BrazeKit/BrazeKit-Swift.h` umbrella header in an ObjC project

### ISSUE THREAD

**Issue by garlapatisatish** [braze-inc/braze-swift-sdk#77]
### Platform

iOS

### Platform Version

15.6.1

### Braze SDK Version

6.6.0

### Xcode Version

14.3.1

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Enable the build settings

SWIFT_TREAT_WARNINGS_AS_ERRORS = YES 
&
GCC_TREAT_WARNINGS_AS_ERRORS = YES

and run the app

### Expected Behavior

No warnings 

### Actual Incorrect Behavior

Showing warnings in `BRZConfigurationLogger`

### Verbose Logs

```shell
Parameter 'message' not found in the function declaration

Parameter 'level' not found in the function declaration
```

### Additional Information

When above flags are set = NO, these just show up as warnings but we use the flags = YES across our apps and we really can't disable the flag. 

<img width="909" alt="Screenshot 2023-08-23 at 10 07 35 PM" src="https://github.com/braze-inc/braze-swift-sdk/assets/60367768/3ce8bbce-4619-4338-8878-06d878c85204">

**Comment by hokstuff** [comment]
Hi @garlapatisatish,

We are able to reproduce this in an ObjC project that imports `<BrazeKit/BrazeKit-Swift.h>` (e.g. when using Cocoapods). It appears that one of the properties of `BRZConfigurationLogger` that we expose in ObjC isn't successfully being translated to the umbrella header. We will investigate into this issue to remove this warning and keep you updated.

Thanks!

**Comment by jerielng** [comment]
Hey @garlapatisatish, we've updated the documentation comments for this property in our latest `7.0.0` release, so you should not be seeing this error any more. Please let us know if you have any further questions. Thank you!
