### ISSUE TITLE
[Bug]: Content Card Classic, text only shows placeholder-image in test send outs. 

### ISSUE THREAD

**Issue by louisebehrenfors-s** [braze-inc/braze-swift-sdk#83]
### Platform

iOS

### Platform Version

iOS 17.0

### Braze SDK Version

7.0.0

### Xcode Version

Xcode 15

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Create a Content Card campaign in Braze. Use the "classic", but do not add any image. So this should be a content-card without image (only text)
  2. Send out a test-card to a device/user. 
  3. The test card received will show as if it has an image (square gray box) 

Does **not** happen when the actual campaign is "launched" and sent out normally. 

### Expected Behavior

Should not show the image placeholder. 

### Actual Incorrect Behavior

Show the image placeholder even though no image provided. 

### Additional Information

Does not happen when the campaign is launched.

**Comment by jerielng** [comment]
Hi @louisebehrenfors-s, could you confirm which version of the Braze SDK you are using? We've recently discovered and addressed this issue, so this should not occur in `7.0.0`. Could you confirm if this still occurs on that version?

I don't think this is mentioned in our changelog, so we'll look into getting that added.

**Comment by jerielng** [comment]
Yep, that is correct! Please let us know if you observe otherwise.

**Comment by louisebehrenfors-s** [comment]
Perfect! Thanks for the quick response!

**Comment by louisebehrenfors-s** [comment]
@jerielng btw, the changelog for the `7.0.0` version has a link to _https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/initial_sdk_setup/swift_idfv?redirected=true_ 
but this link doesn't work, it there another one to get more info around this breaking change?

" 
The useUUIDAsDeviceId configuration is now enabled by default.
For more details on the impacts, refer to this [Collecting IDFV - Swift](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/swift_idfv/).
"

**Comment by jerielng** [comment]
Hey @louisebehrenfors-s, thanks for pointing that out. This should be the correct [link](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/analytics/swift_idfv#collecting-idfv). We'll get that updated as well.
