### ISSUE TITLE
[Bug]: Localization issues on push notification action buttons

### ISSUE THREAD

**Issue by 3a4oT** [braze-inc/braze-swift-sdk#86]
### Platform

iOS

### Platform Version

iOS 17.0.3

### Braze SDK Version

7.1.0

### Xcode Version

Xcode 15.0

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

  1. Integrate Braze SDK and implement push notification functionality using manual flow.
  2. Run the app, and trigger a push notification campaign.

### Expected Behavior

 Should display button labels like:

- Accept
- Decline

### Actual Incorrect Behavior

![localizationBug](https://github.com/braze-inc/braze-swift-sdk/assets/4073499/c3ee17dd-2dee-4206-bffd-91350d67460a)

### Additional Information

Please note that Braze SDK backed to the internal swift package library (used with TCA as a dependency). Maybe default localised strings can't be loaded because of it since when we are on swift package level we should load resources like ```Bundle(.module) instead of Bundle(.main)```??

**Comment by hokstuff** [comment]
Hi @3a4oT,

Thank you for raising this issue! We have filed at ticket to look at it internally.

> Integrate Braze SDK and implement push notification functionality using manual flow

To clarify, when you say `using manual flow`, are you referencing that you integrated the Braze SDK without a package manager (SPM, Cocoapods), or are you referencing something else? Have you been able to been able to repro this when using a package manager?

**Comment by 3a4oT** [comment]
Hey @hokstuff. Yes, I'm using SPM as the package manager. By "manual" flow I mean [Manual push integration](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/push_notifications/integration/#manual-push-integration) from documentation. So no `swizzling` and  no `configuration.push.automation = true` (:

**Comment by 3a4oT** [comment]
More context: I integrated BrazeSDK in my own `swift package` and proxy needed API to it, then from iOS target, I call my library, which under the hood calls Braze API. I hope it does make sense to you.

**Comment by jerielng** [comment]
Thanks for the additional info! If the manual integration refers to just the push feature, I don't think that should have any impact on the localization, but if you did some additional steps to proxy the Swift package into your project, it's possible that the bundle may not be accessible by default. Are you able to locate where the bundle is in your project hierarchy and maybe assign its location to the [overrideResourceBundle](https://github.com/braze-inc/braze-swift-sdk/blob/d2b2407bb184e1eded6209458be94e7761ed4b91/Sources/BrazeUI/Resources.swift#L9)? We [added](https://github.com/braze-inc/braze-swift-sdk/blob/d2b2407bb184e1eded6209458be94e7761ed4b91/CHANGELOG.md?plain=1#L206-L210) this as of `5.11.2` that allows integrations with a little more complex setups to control this piece more granularly.

**Comment by 3a4oT** [comment]
Also, what is weird is that I haven't found any occurrences of `braze-swift-sdk_BrazeKitResources`

Can it be related [to this #if SWIFT_PACKAGE block](https://github.com/braze-inc/braze-swift-sdk/blob/d2b2407bb184e1eded6209458be94e7761ed4b91/Sources/BrazeUICompat/ABKUIUtils/ABKUIUtils.m#L27)?

**Comment by 3a4oT** [comment]
OK, after checking consumer code I found the issue, and it's NOT related to BrazeSDK. The issue was related to swizzling Bundles `localizedString(forKey:value:table:)`. The issue can be closed. Thanks everyone

**Comment by jerielng** [comment]
Thanks for confirming! We'll go ahead and close it but feel free to reach out again if you have more questions!
