### ISSUE TITLE
[Bug]: duplicate symbols for architecture arm64 when using -ObjC flag

### ISSUE THREAD

**Issue by azilbershtein** [braze-inc/braze-swift-sdk#9]
### Platform

iOS

### Platform Version

15.5

### Braze SDK Version

5.2.0

### Xcode Version

13.4.1

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

1. Open project with -ObjC on the target level
2. Add Braze via SPM - I use BrazeKit, BrazeUI and Braz
3. You'll get the duplicate symbols error and the project won't compile
Attaching an example app:
[TestApp.zip](https://github.com/braze-inc/braze-swift-sdk/files/9388052/TestApp.zip)
eNotificationService

### Expected Behavior

Successful compilcation

### Actual Incorrect Behavior

The project compilation failed

### Verbose Logs

```shell
Too long to paste, thats the start of it:
duplicate symbol 'enum case for _BrazeAssetsClient.AssetsClient.FetchPolicy.cacheElseLoad(_BrazeAssetsClient.AssetsClient.FetchPolicy.Type) -> _BrazeAssetsClient.AssetsClient.FetchPolicy' in:
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeKit.framework/BrazeKit(BrazeKit-arm64-master.o)
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeNotificationService.framework/BrazeNotificationService(BrazeNotificationService-arm64-master.o)
duplicate symbol 'static _BrazeAssetsClient.AssetsClient.FetchPolicy.== infix(_BrazeAssetsClient.AssetsClient.FetchPolicy, _BrazeAssetsClient.AssetsClient.FetchPolicy) -> Swift.Bool' in:
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeKit.framework/BrazeKit(BrazeKit-arm64-master.o)
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeNotificationService.framework/BrazeNotificationService(BrazeNotificationService-arm64-master.o)
duplicate symbol '_BrazeAssetsClient.AssetsClient.FetchPolicy.hash(into: inout Swift.Hasher) -> ()' in:
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeKit.framework/BrazeKit(BrazeKit-arm64-master.o)
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeNotificationService.framework/BrazeNotificationService(BrazeNotificationService-arm64-master.o)
duplicate symbol '_BrazeAssetsClient.AssetsClient.FetchPolicy.policy.getter : __C.NSURLRequestCachePolicy' in:
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeKit.framework/BrazeKit(BrazeKit-arm64-master.o)
    /Users/azilbershtein/Library/Developer/Xcode/DerivedData/TestApp-bpaqwksyrjooaqgxyasdeygsestm/Build/Products/Debug-iphonesimulator/BrazeNotificationService.framework/BrazeNotificationService(BrazeNotificationService-arm64-master.o)
```

**Comment by lowip** [comment]
Hi @azilbershtein, thanks for opening this issue.

The `BrazeNotificationService` module is not meant to be integrated in your main application. It should be added to a [_Notification Service Extension_](https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension) instead.

See our [_Rich Push Notifications_](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b2-rich-push-notifications) tutorial and our _PushNotifications_ / _PushNotificationsServiceExtension_ [Examples](https://github.com/braze-inc/braze-swift-sdk/tree/main/Examples) projects.

Your main application should link against:
- `BrazeKit`
- `BrazeUI` (optional, if using the Braze-provided UI)
- `BrazeLocation` (optional, if using the location features)

Once you remove `BrazeNotificationService` from your main application, you will be able to compile it.

Best,

**Comment by azilbershtein** [comment]
Thanks.
We have some question regarding migration from AppBoy, who can help with it?

**Comment by lowip** [comment]
Hi @azilbershtein,

Feel free to open a new issue here or email support@braze.com.
