### ISSUE TITLE
[Bug]: Crashing on tvOS 15 at launch

### ISSUE THREAD

**Issue by brenoangelotti-paramount** [braze-inc/braze-swift-sdk#96]
### Platform

Other

### Platform Version

tvOS 15.0.0

### Braze SDK Version

6.6.0

### Xcode Version

Xcode 15.0

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

1. Add and configure BrazeKit to tvOS app;
2. Run the app.

### Expected Behavior

App should run normally

### Actual Incorrect Behavior

App crashes on launch with 
`dyld[43471]: Symbol not found: _$sSo13UIApplicationC5UIKitE33openNotificationSettingsURLStringSSvgZ`

### Additional Information

Due to missing debugging symbols, I had to go on a hunt for the SDK causing the call to `openNotificationSettingsURLString`, which is [only available on tvOS 16+](https://developer.apple.com/documentation/uikit/uiapplication/4013180-opennotificationsettingsurlstrin). Once I removed BrazeKit, the app run without crashing at startup. I have tested up to version 7.4.0, the issue persists there.

**Comment by jacksonemiller** [comment]
Hi @brenoangelotti-paramount, thank you very much for bringing this to our attention. I was able to reproduce the crash exactly as you described. We will look into this and keep you updated as we work on a fix.

Thank you!

**Comment by jacksonemiller** [comment]
Hi. Just wanted to let you know that we'll be including a fix for this as part of our next release. We'll let you know when we release the next version.

**Comment by jerielng** [comment]
Hi @brenoangelotti-paramount, we've just released version [7.5.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/7.5.0), which contains a fix for this issue. I'll close this thread out, but feel free to open a new one if you have any additional questions. Thank you!
