### ISSUE TITLE
[Bug]: BrazeInAppMessageUI, incorrect deletion of messages from the stack

### ISSUE THREAD

**Issue by alexeyshevel** [braze-inc/braze-swift-sdk#97]
### Platform

iOS

### Platform Version

iOS 17

### Braze SDK Version

7.4.0

### Xcode Version

15.1.0

### Computer Processor

Apple (M1)

### Repro Rate

100%

### Steps To Reproduce

Example:
  1. Check file BrazeIn.AppMessageUI.
  2. The prepareAndPresent method in line 148 does not remove the message from the stack.

### Expected Behavior

The prepareAndPresent method in file BrazeIn.AppMessageUI in line 148 must remove the message from the stack.
In my case it works if I replace the code with this one:
`stack.removeAll { $0.data.id == message.data.id }`

### Actual Incorrect Behavior

The prepareAndPresent method in file BrazeIn.AppMessageUI in line 148 does not remove the message from the stack.
`stack.removeAll { $0 == message }`
There are probably issues in the Equatable protocol implementation for Braze.InAppMessage.

**Comment by jacksonemiller** [comment]
Hi there @alexeyshevel. We just released a fix for this in version 7.6.0 of the Swift SDK. I'm going to go ahead and close this thread for now, but feel free to re-open it or contact us if you have any other issues. Thanks again for the bug report.
