### ISSUE TITLE
[Feature]: Add Privacy Manifest to Braze

### ISSUE THREAD

**Issue by micahcharlesbrown** [braze-inc/braze-swift-sdk#98]
### What problem are you facing?

Apple is requiring app developers and third party SDKs to declare their use of the Required Reason APIs via a Privacy Manifest.

Is Braze planning to add this to the swift SDK? And if not, could it be added? Thanks!

[Privacy Manifest - Apple Documents](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)
[Required Reason API Documents](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

### Workarounds

N/A

### Ideal Solution

Privacy manifest for required reason api uses added

**Comment by jacksonemiller** [comment]
Hi there. We have been preparing to address the upcoming changes. Braze itself is not on [the list of privacy-impacting SDKs released by Apple](https://developer.apple.com/support/third-party-SDK-requirements/), nevertheless, we are still working on a solution that we think will put us in line with Apple's recommendations while also giving clients more granular control over user data. We will note the release of the feature in a future changelog.

**Comment by micahcharlesbrown** [comment]
Thanks for the info - much appreciated

**Comment by jerielng** [comment]
Hey @micahcharlesbrown, we've just released version [7.5.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/7.5.0), which contains the privacy manifests for Braze. In a future update, we will also be releasing even more fine-tuned configurations that will allow you to customize your data collection practices if you wish.

I'll go ahead and close out this issue, but feel free to open a new one if you have additional questions or concerns. Thank you!

**Comment by pavm035** [comment]
@jerielng  Hi I would like to know if this SDK is targeted for signature requirement or is it only for xcframeworks ?
https://developer.apple.com/videos/play/wwdc2023/10061

**Comment by pavm035** [comment]
@jerielng  Thanks for confirmng, we have contacted apple internally and they confirmed that if your SDK is listed in the officila or not, this rule still apply, interestingly i found in the apple forum that apple engineer claims the same
https://developer.apple.com/forums/thread/743650?answerId=776588022#776588022

**Comment by jerielng** [comment]
Thanks @pavm035! For this reason, we have provided all the necessary resources as of version 7.5.0+, so you should have everything you need from our SDK to comply with Apple's policies. Feel free to let us know if you have any further questions.

**Comment by pavm035** [comment]
@jerielng Thanks for confirming, i hope it will fix the issue for us
